package fr.jmini.empoa.specs;

public enum ElementType {
    Components,
    ExternalDocumentation,
    OpenAPI,
    Operation,
    PathItem,
    Paths,
    Callback,
    Example,
    Header,
    Contact,
    Info,
    License,
    Link,
    Content,
    Discriminator,
    Encoding,
    MediaType,
    Schema,
    XML,
    Parameter,
    RequestBody,
    APIResponse,
    APIResponses,
    OAuthFlow,
    OAuthFlows,
    Scopes,
    SecurityRequirement,
    SecurityScheme,
    Server,
    ServerVariable,
    ServerVariables,
    Tag
}
